# DSV - Lab 2

*March 6+13, 2026*

---

## Datasets

### Temperatures

Fahrenheit temperatures in a few locations around the world

In [123]:
# import libraries
import pandas as pd

In [124]:
temp = [35, 88, 42, 84, 81, 30]
city = ["Beijing", "Lagos", "Paris", 
          "Rio de Janeiro", "San Juan", "Toronto"]
city_temps = pd.DataFrame({"name": city, "temperature_F": temp}).convert_dtypes()
city_temps

             name  temperature_F
0         Beijing             35
1           Lagos             88
2           Paris             42
3  Rio de Janeiro             84
4        San Juan             81
5         Toronto             30

### Firearm murders

The dataset reports the murders by firearms in U.S.A. in 2023 in each state.

In [125]:

murders = pd.read_csv("data/murders.csv", dtype={"Region": "category"}).convert_dtypes()
murders.head()

        State Region  Population Abbr.  Deaths
0     Alabama  South     5117850    AL    1292
1      Alaska   West      734654    AK     176
2     Arizona   West     7452073    AZ    1419
3    Arkansas  South     3069856    AR     671
4  California   West    39181667    CA    3209

Sources:

- https://www.cdc.gov/nchs/state-stats/deaths/firearms.html?CDC_AAref_Val=https://www.cdc.gov/nchs/pressroom/sosmap/firearm_mortality/firearm.htm
- https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/state/totals/NST-EST2025-ALLDATA.csv

## Exercise 1 - Usage of DataFrames

### Data frames

DataFrames (`pd.DataFrame`) are the basic tool in which tabular data from various sources are stored.

Most of the processing and analysis starts from data stored in DataFrames.

Print the initial portion of the dataset using the `.head()` method

In [126]:
murders.head()

        State Region  Population Abbr.  Deaths
0     Alabama  South     5117850    AL    1292
1      Alaska   West      734654    AK     176
2     Arizona   West     7452073    AZ    1419
3    Arkansas  South     3069856    AR     671
4  California   West    39181667    CA    3209

# TODO: insert code to print the initial portion of the dataset

You can access individual columns of the DataFrame using bracket notation `df['column']` (or alternatively dot notation `df.column`), both return a Series.

Try gettin the content of the *Abbr.* column using both methods.

In [127]:
murders["Abbr."]

0     AL
1     AK
2     AZ
3     AR
4     CA
5     CO
6     CT
7     DE
8     DC
9     FL
10    GA
11    HI
12    ID
13    IL
14    IN
15    IA
16    KS
17    KY
18    LA
19    ME
20    MD
21    MA
22    MI
23    MN
24    MS
25    MO
26    MT
27    NE
28    NV
29    NH
30    NJ
31    NM
32    NY
33    NC
34    ND
35    OH
36    OK
37    OR
38    PA
39    RI
40    SC
41    SD
42    TN
43    TX
44    UT
45    VT
46    VA
47    WA
48    WV
49    WI
50    WY
Name: Abbr., dtype: string

To understand the data types of the 5 columns, you can use the `.dtypes` attribute or the `.info()` method on the DataFrame.

In [128]:
print(murders.dtypes)
# or
print(murders.info())

State           string
Region        category
Population       Int64
Abbr.           string
Deaths           Int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   State       51 non-null     string
 1   Region      51 non-null     category
 2   Population  51 non-null     Int64
 3   Abbr.       51 non-null     string
 4   Deaths      51 non-null     Int64
dtypes: Int64(2), category(1), string(2)
memory usage: 2.1 KB
None

The *region* column, unlike the two that precede it in the DataFrame, is of type `category` (similar to R's factor).
Given a categorical column, you can get the categories (i.e., the possible values) using the `.cat.categories` attribute.

Print the categories of the *region* column, and the minimum and maximum of the number of murders (*total* column).

In [129]:
print(murders["Region"].cat.categories)
print(f"Min n° of deaths: {murders["Deaths"].min()}")
print(f"Max n° of deaths: {murders["Deaths"].max()}")

Index(['Midwest', 'Northeast', 'South', 'West'], dtype='str')
Min n° of deaths: 58
Max n° of deaths: 4561

To count the different values of a column, you can use the `.value_counts()` method.

Count the frequencies of the different levels of the *region* column.

In [130]:
murders["Region"].value_counts()

Region
South        17
West         13
Midwest      12
Northeast     9
Name: count, dtype: int64

Count the frequencies of the different levels of the *region* column, expressing them also as proportions (fractions that sum to 1) and as percentages (sum = 100%). Use `.value_counts(normalize=True)` for proportions.

In [131]:
murders["Region"].value_counts(normalize=True)

Region
South        0.333333
West         0.254902
Midwest      0.235294
Northeast    0.176471
Name: proportion, dtype: float64

To get an overview, you can use the `.describe()` method which prints, in addition to the data type, some summary information.

In [132]:
murders.describe()

           Population      Deaths
count            51.0        51.0
mean   6603040.235294  879.705882
std    7517244.464112  892.696394
min          584666.0        58.0
25%         1870266.5       225.0
50%         4549953.0       642.0
75%         7645364.0      1259.5
max        39181667.0      4561.0

### Sorting

Sort the *"variable"* (or column) *population* from smallest to largest value using `.sort_values()`

In [133]:
murders.sort_values(by="Population")

                   State     Region  Population Abbr.  Deaths
50               Wyoming       West      584666    WY     130
45               Vermont  Northeast      647722    VT      83
8   District of Columbia      South      682559    DC     225
1                 Alaska       West      734654    AK     176
34          North Dakota    Midwest      787071    ND     103
41          South Dakota    Midwest      917739    SD     112
7               Delaware      South     1035354    DE     124
39          Rhode Island  Northeast     1101183    RI      58
26               Montana       West     1130612    MT     247
29         New Hampshire  Northeast     1401530    NH     143
19                 Maine  Northeast     1401992    ME     200
11                Hawaii       West     1434950    HI      73
48         West Virginia      South     1770036    WV     315
12                 Idaho       West     1970497    ID     356
27              Nebraska    Midwest     1988172    NE     213
31            New Mexico       West     2119349    NM     530
24           Mississippi      South     2942470    MS     844
16                Kansas    Midwest     2949749    KS     475
3               Arkansas      South     3069856    AR     671
28                Nevada       West     3211077    NV     616
15                  Iowa    Midwest     3214739    IA     341
44                  Utah       West     3449259    UT     489
6            Connecticut  Northeast     3641369    CT     225
36              Oklahoma      South     4062716    OK     814
37                Oregon       West     4250392    OR     642
17              Kentucky      South     4549953    KY     841
18             Louisiana      South     4598777    LA    1261
0                Alabama      South     5117850    AL    1292
40        South Carolina      South     5390798    SC    1019
23             Minnesota    Midwest     5752998    MN     525
5               Colorado       West     5912240    CO    1019
49             Wisconsin    Midwest     5930350    WI     762
20              Maryland      South     6204927    MD     737
25              Missouri    Midwest     6205956    MO    1324
14               Indiana    Midwest     6881373    IN    1258
21         Massachusetts  Northeast     7073479    MA     270
42             Tennessee      South     7153029    TN    1587
2                Arizona       West     7452073    AZ    1419
47            Washington       West     7838655    WA    1053
46              Virginia      South     8732034    VA    1237
30            New Jersey  Northeast     9395315    NJ     430
22              Michigan    Midwest    10062124    MI    1384
33        North Carolina      South    10871849    NC    1803
10               Georgia      South    11063669    GA     207
35                  Ohio    Midwest    11808390    OH    1768
13              Illinois    Midwest    12633389    IL    1691
38          Pennsylvania  Northeast    13009406    PA    1807
32              New York  Northeast    19786543    NY     943
9                Florida      South    22929248    FL    3253
43                 Texas      South    30719247    TX    4561
4             California       West    39181667    CA    3209

Sort the state names *state* based on their respective population, in descending order. You should get a Series with the most populous state in first position, which is Alabama with 39,181,667 inhabitants, and the least populous in last position, which is Wyoming with 584,666 inhabitants.

To have the name of the states as index (instead of the numeric index) you need to start with a dataframe with such an index, you can set the index with `set_index()` on the DataFrame object.

In [134]:
murders.sort_values(by="Population",ascending=False).set_index(murders["State"])["Population"]

State
Alabama                 39181667
Alaska                  30719247
Arizona                 22929248
Arkansas                19786543
California              13009406
Colorado                12633389
Connecticut             11808390
Delaware                11063669
District of Columbia    10871849
Florida                 10062124
Georgia                  9395315
Hawaii                   8732034
Idaho                    7838655
Illinois                 7452073
Indiana                  7153029
Iowa                     7073479
Kansas                   6881373
Kentucky                 6205956
Louisiana                6204927
Maine                    5930350
Maryland                 5912240
Massachusetts            5752998
Michigan                 5390798
Minnesota                5117850
Mississippi              4598777
Missouri                 4549953
Montana                  4250392
Nebraska                 4062716
Nevada                   3641369
New Hampshire            3449259
New Jersey               3214739
New Mexico               3211077
New York                 3069856
North Carolina           2949749
North Dakota             2942470
Ohio                     2119349
Oklahoma                 1988172
Oregon                   1970497
Pennsylvania             1770036
Rhode Island             1434950
South Carolina           1401992
South Dakota             1401530
Tennessee                1130612
Texas                    1101183
Utah                     1035354
Vermont                   917739
Virginia                  787071
Washington                734654
West Virginia             682559
Wisconsin                 647722
Wyoming                   584666
Name: Population, dtype: Int64

Finally, sort the entire DataFrame based on the number of murders (*Deaths*)

In [135]:
murders.sort_values(by="Deaths")

                   State     Region  Population Abbr.  Deaths
39          Rhode Island  Northeast     1101183    RI      58
11                Hawaii       West     1434950    HI      73
45               Vermont  Northeast      647722    VT      83
34          North Dakota    Midwest      787071    ND     103
41          South Dakota    Midwest      917739    SD     112
7               Delaware      South     1035354    DE     124
50               Wyoming       West      584666    WY     130
29         New Hampshire  Northeast     1401530    NH     143
1                 Alaska       West      734654    AK     176
19                 Maine  Northeast     1401992    ME     200
10               Georgia      South    11063669    GA     207
27              Nebraska    Midwest     1988172    NE     213
8   District of Columbia      South      682559    DC     225
6            Connecticut  Northeast     3641369    CT     225
26               Montana       West     1130612    MT     247
21         Massachusetts  Northeast     7073479    MA     270
48         West Virginia      South     1770036    WV     315
15                  Iowa    Midwest     3214739    IA     341
12                 Idaho       West     1970497    ID     356
30            New Jersey  Northeast     9395315    NJ     430
16                Kansas    Midwest     2949749    KS     475
44                  Utah       West     3449259    UT     489
23             Minnesota    Midwest     5752998    MN     525
31            New Mexico       West     2119349    NM     530
28                Nevada       West     3211077    NV     616
37                Oregon       West     4250392    OR     642
3               Arkansas      South     3069856    AR     671
20              Maryland      South     6204927    MD     737
49             Wisconsin    Midwest     5930350    WI     762
36              Oklahoma      South     4062716    OK     814
17              Kentucky      South     4549953    KY     841
24           Mississippi      South     2942470    MS     844
32              New York  Northeast    19786543    NY     943
5               Colorado       West     5912240    CO    1019
40        South Carolina      South     5390798    SC    1019
47            Washington       West     7838655    WA    1053
46              Virginia      South     8732034    VA    1237
14               Indiana    Midwest     6881373    IN    1258
18             Louisiana      South     4598777    LA    1261
0                Alabama      South     5117850    AL    1292
25              Missouri    Midwest     6205956    MO    1324
22              Michigan    Midwest    10062124    MI    1384
2                Arizona       West     7452073    AZ    1419
42             Tennessee      South     7153029    TN    1587
13              Illinois    Midwest    12633389    IL    1691
35                  Ohio    Midwest    11808390    OH    1768
33        North Carolina      South    10871849    NC    1803
38          Pennsylvania  Northeast    13009406    PA    1807
4             California       West    39181667    CA    3209
9                Florida      South    22929248    FL    3253
43                 Texas      South    30719247    TX    4561

----

## EXERCISE 2 - Operations on DataFrames

### Vectorized arithmetic

Starting from the temperature DataFrame (`city_temps`), calculate the temperatures in Celsius from those expressed in Fahrenheit.

The conversion formula is:

$$C = \frac{5}{9} \cdot ( F - 32  )$$

In [136]:
temperature_df=city_temps.drop(["name"],axis=1)
temperature_df["temperature_C"] = temperature_df["temperature_F"].map(lambda t: 5/9*(t-32))
temperature_df

   temperature_F  temperature_C
0             35       1.666667
1             88      31.111111
2             42       5.555556
3             84      28.888889
4             81      27.222222
5             30      -1.111111

Using the same conversion, add a column to the temperature DataFrame with the temperatures in Celsius. Would rounding be useful?

Hint: you can assign a new column using `df['new_column'] = values`

In [137]:
city_temps["temperature_C"] = city_temps["temperature_F"].map(lambda t: round(5/9*(t-32),2))
city_temps

             name  temperature_F  temperature_C
0         Beijing             35           1.67
1           Lagos             88          31.11
2           Paris             42           5.56
3  Rio de Janeiro             84          28.89
4        San Juan             81          27.22
5         Toronto             30          -1.11

Calculate (and add as a new column *rate*) the murder rate per 100,000 people in the murders DataFrame and show the updated DataFrame

In [138]:
murders["Rate"] = murders["Deaths"]*100000/murders["Population"]
murders.sort_values(by="Rate")

                   State     Region  Population Abbr.  Deaths       Rate
10               Georgia      South    11063669    GA     207   1.870989
21         Massachusetts  Northeast     7073479    MA     270   3.817075
30            New Jersey  Northeast     9395315    NJ     430   4.576749
32              New York  Northeast    19786543    NY     943   4.765865
11                Hawaii       West     1434950    HI      73   5.087285
39          Rhode Island  Northeast     1101183    RI      58   5.267063
6            Connecticut  Northeast     3641369    CT     225   6.178995
4             California       West    39181667    CA    3209   8.190055
23             Minnesota    Midwest     5752998    MN     525   9.125677
29         New Hampshire  Northeast     1401530    NH     143  10.203135
15                  Iowa    Midwest     3214739    IA     341  10.607393
27              Nebraska    Midwest     1988172    NE     213  10.713359
20              Maryland      South     6204927    MD     737  11.877658
7               Delaware      South     1035354    DE     124   11.97658
41          South Dakota    Midwest      917739    SD     112  12.203905
45               Vermont  Northeast      647722    VT      83  12.814139
49             Wisconsin    Midwest     5930350    WI     762  12.849157
34          North Dakota    Midwest      787071    ND     103  13.086494
13              Illinois    Midwest    12633389    IL    1691  13.385165
47            Washington       West     7838655    WA    1053  13.433427
22              Michigan    Midwest    10062124    MI    1384  13.754551
38          Pennsylvania  Northeast    13009406    PA    1807   13.88995
46              Virginia      South     8732034    VA    1237   14.16623
44                  Utah       West     3449259    UT     489  14.176958
9                Florida      South    22929248    FL    3253   14.18712
19                 Maine  Northeast     1401992    ME     200  14.265417
43                 Texas      South    30719247    TX    4561  14.847369
35                  Ohio    Midwest    11808390    OH    1768  14.972405
37                Oregon       West     4250392    OR     642  15.104489
16                Kansas    Midwest     2949749    KS     475  16.103065
33        North Carolina      South    10871849    NC    1803  16.584116
5               Colorado       West     5912240    CO    1019   17.23543
48         West Virginia      South     1770036    WV     315  17.796248
12                 Idaho       West     1970497    ID     356  18.066508
14               Indiana    Midwest     6881373    IN    1258  18.281235
17              Kentucky      South     4549953    KY     841  18.483707
40        South Carolina      South     5390798    SC    1019  18.902582
2                Arizona       West     7452073    AZ    1419  19.041681
28                Nevada       West     3211077    NV     616  19.183595
36              Oklahoma      South     4062716    OK     814  20.035858
25              Missouri    Midwest     6205956    MO    1324  21.334344
26               Montana       West     1130612    MT     247  21.846575
3               Arkansas      South     3069856    AR     671  21.857703
42             Tennessee      South     7153029    TN    1587  22.186405
50               Wyoming       West      584666    WY     130  22.234917
1                 Alaska       West      734654    AK     176  23.956856
31            New Mexico       West     2119349    NM     530  25.007679
0                Alabama      South     5117850    AL    1292  25.244976
18             Louisiana      South     4598777    LA    1261  27.420334
24           Mississippi      South     2942470    MS     844  28.683385
8   District of Columbia      South      682559    DC     225  32.964183

What is the average murder rate?

In [139]:
print(round(murders["Rate"].mean(),6))

15.36953

You can use the `.quantile()` method or `.describe()` to calculate the five-number summary (minimum, 1st quartile, median, 3rd quartile, maximum) of a column's data.
What are the 5 numbers that summarize the *rate* column?

In [140]:
min = murders["Rate"].min()
quartile_1 = murders["Rate"].quantile(0.25)
median = murders["Rate"].median()
quartile_3 = murders["Rate"].quantile(0.75)
max = murders["Rate"].max()

### Masking

How many states have a murder rate below the first quartile (calculated above)?

In [141]:
mask = murders["Rate"] < quartile_1
print(mask.sum())

13

Using a boolean mask, select the portion of the DataFrame that corresponds to the states in the first quartile for murder rate.

In [142]:
murders[mask]

            State     Region  Population Abbr.  Deaths       Rate
4      California       West    39181667    CA    3209   8.190055
6     Connecticut  Northeast     3641369    CT     225   6.178995
10        Georgia      South    11063669    GA     207   1.870989
11         Hawaii       West     1434950    HI      73   5.087285
15           Iowa    Midwest     3214739    IA     341  10.607393
20       Maryland      South     6204927    MD     737  11.877658
21  Massachusetts  Northeast     7073479    MA     270   3.817075
23      Minnesota    Midwest     5752998    MN     525   9.125677
27       Nebraska    Midwest     1988172    NE     213  10.713359
29  New Hampshire  Northeast     1401530    NH     143  10.203135
30     New Jersey  Northeast     9395315    NJ     430   4.576749
32       New York  Northeast    19786543    NY     943   4.765865
39   Rhode Island  Northeast     1101183    RI      58   5.267063

Report the data for the states in the `"West"` region that are in the first quartile, again for murder rate.

Hint: build a boolean mask by combining the two conditions with logical operators (`&` for AND, `|` for OR)

In [143]:
mask_2 = murders["Region"]=="West"
murders[mask & mask_2]

         State Region  Population Abbr.  Deaths      Rate
4   California   West    39181667    CA    3209  8.190055
11      Hawaii   West     1434950    HI      73  5.087285

Use the `.isin()` method to create a boolean mask that identifies states that have abbreviations MA, ME, MI, MO, MU. And calculate the number of identified states.

In [144]:
mask_3 = murders["Abbr."].isin(["MA","ME","MI","MO","MU"])
murders[mask_3]

            State     Region  Population Abbr.  Deaths       Rate
19          Maine  Northeast     1401992    ME     200  14.265417
21  Massachusetts  Northeast     7073479    MA     270   3.817075
22       Michigan    Midwest    10062124    MI    1384  13.754551
25       Missouri    Midwest     6205956    MO    1324  21.334344

Use the same method to find out which of the abbreviations correspond to real abbreviations and list them.

In [145]:
abbreviations = murders["Abbr."].unique()
pd.Series(abbreviations)

0     AL
1     AK
2     AZ
3     AR
4     CA
5     CO
6     CT
7     DE
8     DC
9     FL
10    GA
11    HI
12    ID
13    IL
14    IN
15    IA
16    KS
17    KY
18    LA
19    ME
20    MD
21    MA
22    MI
23    MN
24    MS
25    MO
26    MT
27    NE
28    NV
29    NH
30    NJ
31    NM
32    NY
33    NC
34    ND
35    OH
36    OK
37    OR
38    PA
39    RI
40    SC
41    SD
42    TN
43    TX
44    UT
45    VT
46    VA
47    WA
48    WV
49    WI
50    WY
dtype: string

## Categorical Binning

The `pd.cut()` function allows you to divide numerical values into intervals (given the boundaries, with upper bound included by default) and assign a label to each interval. The result is a categorical Series.

In [146]:
## Example of using pd.cut()
bins = [0, 2e6, 1e7, 5e7]
labels = ["small", "medium", "large"]
pd.cut(murders["Population"], bins=bins, labels=labels, ordered=True).value_counts(sort=False)

Population
small     15
medium    26
large     10
Name: count, dtype: int64

Assign a level (low, medium, high) to the murder rate corresponding to the intervals (0,10], (10,20], (20,40], and add this classification as a new column *"Rate class"*.

In [147]:
rate_bins = [0,10,20,40]
rate_labels = ["low","medium","high"]
murders["Rate class"] = pd.cut(murders["Rate"],bins=rate_bins,labels=rate_labels)
murders

,State,Region,Population,Abbr.,Deaths,Rate,Rate class
0,Alabama,South,5117850,AL,1292,25.244976,high
1,Alaska,West,734654,AK,176,23.956856,high
2,Arizona,West,7452073,AZ,1419,19.041681,medium
3,Arkansas,South,3069856,AR,671,21.857703,high
4,California,West,39181667,CA,3209,8.190055,low
5,Colorado,West,5912240,CO,1019,17.23543,medium
6,Connecticut,Northeast,3641369,CT,225,6.178995,low
7,Delaware,South,1035354,DE,124,11.97658,medium
8,District of Columbia,South,682559,DC,225,32.964183,high
9,Florida,South,22929248,FL,3253,14.18712,medium
10,Georgia,South,11063669,GA,207,1.870989,low
11,Hawaii,West,1434950,HI,73,5.087285,low
12,Idaho,West,1970497,ID,356,18.066508,medium
13,Illinois,Midwest,12633389,IL,1691,13.385165,medium
14,Indiana,Midwest,6881373,IN,1258,18.281235,medium
15,Iowa,Midwest,3214739,IA,341,10.607393,medium
16,Kansas,Midwest,2949749,KS,475,16.103065,medium
17,Kentucky,South,4549953,KY,841,18.483707,medium
18,Louisiana,South,4598777,LA,1261,27.420334,high
19,Maine,Northeast,1401992,ME,200,14.265417,medium
20,Maryland,South,6204927,MD,737,11.877658,medium
21,Massachusetts,Northeast,7073479,MA,270,3.817075,low
22,Michigan,Midwest,10062124,MI,1384,13.754551,medium
23,Minnesota,Midwest,5752998,MN,525,9.125677,low
24,Mississippi,South,2942470,MS,844,28.683385,high
25,Missouri,Midwest,6205956,MO,1324,21.334344,high
26,Montana,West,1130612,MT,247,21.846575,high
27,Nebraska,Midwest,1988172,NE,213,10.713359,medium
28,Nevada,West,3211077,NV,616,19.183595,medium
29,New Hampshire,Northeast,1401530,NH,143,10.203135,medium
30,New Jersey,Northeast,9395315,NJ,430,4.576749,low
31,New Mexico,West,2119349,NM,530,25.007679,high
32,New York,Northeast,19786543,NY,943,4.765865,low
33,North Carolina,South,10871849,NC,1803,16.584116,medium
34,North Dakota,Midwest,787071,ND,103,13.086494,medium
35,Ohio,Midwest,11808390,OH,1768,14.972405,medium
36,Oklahoma,South,4062716,OK,814,20.035858,high
37,Oregon,West,4250392,OR,642,15.104489,medium
38,Pennsylvania,Northeast,13009406,PA,1807,13.88995,medium
39,Rhode Island,Northeast,1101183,RI,58,5.267063,low
40,South Carolina,South,5390798,SC,1019,18.902582,medium
41,South Dakota,Midwest,917739,SD,112,12.203905,medium
42,Tennessee,South,7153029,TN,1587,22.186405,high
43,Texas,South,30719247,TX,4561,14.847369,medium
44,Utah,West,3449259,UT,489,14.176958,medium
45,Vermont,Northeast,647722,VT,83,12.814139,medium
46,Virginia,South,8732034,VA,1237,14.16623,medium
47,Washington,West,7838655,WA,1053,13.433427,medium
48,West Virginia,South,1770036,WV,315,17.796248,medium
49,Wisconsin,Midwest,5930350,WI,762,12.849157,medium
50,Wyoming,West,584666,WY,130,22.234917,high

Calculate the frequencies of the different ratings:

In [148]:
murders["Rate class"].value_counts().sort_index()

Rate class
low        9
medium    30
high      12
Name: count, dtype: int64

Show the names of the states with a high rate

In [149]:
mask_rate = murders["Rate class"]=="high"
murders[mask_rate]

,State,Region,Population,Abbr.,Deaths,Rate,Rate class
0,Alabama,South,5117850,AL,1292,25.244976,high
1,Alaska,West,734654,AK,176,23.956856,high
3,Arkansas,South,3069856,AR,671,21.857703,high
8,District of Columbia,South,682559,DC,225,32.964183,high
18,Louisiana,South,4598777,LA,1261,27.420334,high
24,Mississippi,South,2942470,MS,844,28.683385,high
25,Missouri,Midwest,6205956,MO,1324,21.334344,high
26,Montana,West,1130612,MT,247,21.846575,high
31,New Mexico,West,2119349,NM,530,25.007679,high
36,Oklahoma,South,4062716,OK,814,20.035858,high
42,Tennessee,South,7153029,TN,1587,22.186405,high
50,Wyoming,West,584666,WY,130,22.234917,high

Show all the details of the states with high rate except the "Rate class" column itself sorted by descending rate

In [150]:
murders[mask_rate].iloc[:,0:6].sort_values(by="Rate",ascending=False)

                   State   Region  Population Abbr.  Deaths       Rate
8   District of Columbia    South      682559    DC     225  32.964183
24           Mississippi    South     2942470    MS     844  28.683385
18             Louisiana    South     4598777    LA    1261  27.420334
0                Alabama    South     5117850    AL    1292  25.244976
31            New Mexico     West     2119349    NM     530  25.007679
1                 Alaska     West      734654    AK     176  23.956856
50               Wyoming     West      584666    WY     130  22.234917
42             Tennessee    South     7153029    TN    1587  22.186405
3               Arkansas    South     3069856    AR     671  21.857703
26               Montana     West     1130612    MT     247  21.846575
25              Missouri  Midwest     6205956    MO    1324  21.334344
36              Oklahoma    South     4062716    OK     814  20.035858

### Grouping

Show the average death rate per region

In [151]:
murders.groupby("Region")["Rate"].mean()

Region
Midwest      13.868063
Northeast     8.419821
South        18.769732
West          17.12042
Name: Rate, dtype: Float64

Use `agg()` to get a DataFrame instead of a Series

In [152]:
rate_per_region = murders.groupby("Region").agg({"Rate":["mean"]})
rate_per_region.droplevel(0,1).reset_index().rename({"mean":"Average Death Ratio"},axis=1)

      Region  Average Death Ratio
0    Midwest            13.868063
1  Northeast             8.419821
2      South            18.769732
3       West             17.12042